POST http://localhost:3001/register
Content-Type: application/json

{
  "user": {
    "email": "rizkiraden616@gmail.com",
    "password": "12345678",
    "first_name": "Raden",
    "last_name": "Rizki",
    "role": "MEMBER"
  }
}

###
POST http://localhost:3001/login
Content-Type: application/json

{
  "email": "test@mail.com",
  "password": "123456"
}